/**
 * config.h
 * Authors: Yun-Sheng Chang
 */

#ifndef CONFIG_H
#define CONFIG_H

#include "ssdconfig.h"

/* ssd configurations */
#define VST_SECTORS_PER_PAGE SECTORS_PER_PAGE
#define VST_PAGES_PER_BLOCK PAGES_PER_BLOCK
#define VST_BLOCKS_PER_BANK BLOCKS_PER_BANK

#define VST_NUM_BANKS NUM_BANKS
#define VST_NUM_BLOCKS (VST_NUM_BANKS * VST_BLOCKS_PER_BANK)
#define VST_NUM_PAGES (VST_NUM_BLOCKS * VST_PAGES_PER_BLOCK)
#define VST_NUM_SECTORS (VST_NUM_PAGES * VST_SECTORS_PER_PAGE)

#define VST_BYTES_PER_SECTOR SECTOR_SIZE
#define VST_BYTES_PER_PAGE (VST_SECTORS_PER_PAGE * VST_BYTES_PER_SECTOR)

#define VST_MAX_LBA MAX_LBA

#define VST_DRAM_BASE DRAM_BASE
#define VST_DRAM_SIZE DRAM_SIZE

#endif // CONFIG_H

